name: emotion_controller
description: "Emotion Controller - AI-powered emotion detection frontend"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  persistent_bottom_nav_bar: ^6.2.1
  camera: ^0.11.0+2
  intl: ^0.19.0
  youtube_player_flutter: ^9.0.0
  http: ^1.2.0
  image: ^4.1.7
  google_mlkit_face_detection: ^0.13.2
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.4
  flutter_inappwebview_windows: ^0.6.0
  uuid: ^4.3.3
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
